#! /bin/sh

chosen=$(printf "  Shutdown\n  Restart\n  Lock" | rofi -window-title "power" -dmenu -i -theme ~/.config/rofi/config.rasi)

case "$chosen" in
	"  Shutdown") shutdown now ;;
	"  Restart") reboot ;;
	"  Lock") betterlockscreen -l blur ;;
	*) exit 1 ;;
esac
