theme = "base16_terminal"

[editor]
line-number = "relative"
mouse = false
bufferline = "multiple"
shell = ["zsh", "-c"]
color-modes = true
completion-replace = true

[editor.file-picker]
hidden = false

[editor.lsp]
snippets=true
auto-signature-help=false

[editor.cursor-shape]
insert = "bar"

[keys.normal]
m = "move_char_left"
n = "move_line_down"
e = "move_line_up"
i = "move_char_right"

s = "move_next_word_start"
S = "move_next_long_word_start"
h = "move_prev_word_start"
H = "move_prev_long_word_start"

t = "move_next_word_end"
T = "move_next_long_word_end"

w = "find_till_char"
W = "till_prev_char"

l = "select_regex"
L = "split_selection"
A-l = "split_selection_on_newline"

"C-e" = "half_page_up"
"C-n" = "half_page_down"

"S-tab" = "insert_at_line_start"
"tab" = "insert_mode"

esc = ["collapse_selection", "keep_primary_selection"]
"?" = "toggle_comments"
C-space = "signature_help"
C-s = ":w"

# todo: changes for jumplist

[keys.normal.b]
s = "surround_add"
m = "match_brackets"
r = "surround_replace"
d = "surround_delete"
a = "select_textobject_around"
i = "select_textobject_inner"

[keys.select.b]
s = "surround_add"
m = "match_brackets"
r = "surround_replace"
d = "surround_delete"
a = "select_textobject_around"
i = "select_textobject_inner"

[keys.select]
m = "extend_char_left"
n = "extend_line_down"
e = "extend_line_up"
i = "extend_char_right"

s = "extend_next_word_start"
S = "extend_next_long_word_start"
h = "extend_prev_word_start"
H = "extend_prev_long_word_start"

t = "extend_next_word_end"
T = "extend_next_long_word_end"

l = "select_regex"
L = "split_selection"
A-l = "split_selection_on_newline"

"C-/" = "toggle_comments"
"C-s" = ":w"

[keys.normal.g]
m = "goto_line_start"
i = "goto_line_end"
o = "goto_implementation"
u = "goto_last_modified_file"
h = "no_op"
l = "no_op"

[keys.select.g]
m = "goto_line_start"
i = "goto_line_end"
o = "goto_implementation"
u = "goto_last_modified_file"
h = "no_op"
l = "no_op"

[keys.insert]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"
C-space = "completion"
C-i = "delete_word_forward"
C-m = "delete_word_backward"
C-l = "kill_to_line_start"
C-u = "kill_to_line_end"
